### ISSUE TITLE
Support LF linebreaks

### ISSUE THREAD

**Issue by fflaten** [lzybkr/ShowPSAst#9]
Only recognizes linebreak with CRLF atm.
Should support LF due to more common use with cross-platform scripts.

**Comment by mklement0** [comment]
@fflaten, as a stopgap, you can patch a current installation of the module as follows:

In `ShowPSAst.psm1`, as currently available via the gallery, replace:

```powershell
            $text = [string]$InputObject
            if (Test-Path -LiteralPath $text)
            {
                $path = Resolve-Path $text
                $InputObject = [System.Management.Automation.Language.Parser]::ParseFile($path.ProviderPath, [ref]$null, [ref]$null)
            }
            else
            {
                $InputObject = [System.Management.Automation.Language.Parser]::ParseInput($text, [ref]$null, [ref]$null)
            }
```

with:

```powershell
            $text = [string]$InputObject
            if (Test-Path -LiteralPath $text)
            {
                # To also support LF-only files, read the file in full and normalize the newlines to CRLF, 
                # which the WinForms textbox control requires for proper display.
                $text = (Get-Content -Raw -LiteralPath $text) -replace '(?<!\r)\n', "`r`n"
            }
            $InputObject = [System.Management.Automation.Language.Parser]::ParseInput($text, [ref]$null, [ref]$null)
```

Given the unknown status of this project (as [you know](https://github.com/lzybkr/ShowPSAst/pull/7#issuecomment-1383184937)), I'm  not submitting a PR.

Generally, it would be nice if a cross-platform, console-based re-implementation were to become part of the [`Microsoft.PowerShell.ConsoleGuiTools`](https://github.com/PowerShell/GraphicalTools/) tools (which currently provide `Out-GridConsoleView` and `Show-ObjectTree`) - see:

* https://github.com/PowerShell/GraphicalTools/issues/244

**Comment by lzybkr** [comment]
@mklement0 - I just don't have much extra time these days.

I should probably just archive the project and hope that someone starts something that works better cross-platform, but I could also consider handing off maintaining this project if someone offered.
